### ISSUE TITLE
Request updated benchmark results

### ISSUE THREAD

**Issue by wenshao** [fabienrenaud/java-json-benchmark#87]
The last update was 5 months ago. Please update the benchmark result.

**Comment by fabienrenaud** [comment]
Feel free to run the benchmark yourself (on aws or standard cloud instances) and update the readmes. All the scripts and links to spreadsheet are available in the repo. Otherwise the next run will likely be around new years. 

One reason I'd run it sooner is if there is a major new player in town, or if there are reports that relative results between libs have changed significantly.

**Comment by wenshao** [comment]
The performance of fastjson2 has been significantly improved, I hope you can update the results

**Comment by fabienrenaud** [comment]
If you could send a PR updating all libs to latest, that’d help me get
started on the next run sooner. Thx.

Fabien

**Comment by fabienrenaud** [comment]
Just uploaded updated benchmarks. Thanks for your help!
